import { AGENTS } from "./agentRouter";

// High-fidelity schema definitions for LLM context
export const TABLE_SCHEMAS: Record<string, string> = {
  sales: `Table: e_com.gold.sales_summary
Description: Summarizes retail transactions, pricing, locations, and category metadata. Use this for all sales, revenue, profit, orders, locations, regional trends, payment structures, and rating queries.
Columns:
- order_id: string (unique order identifier)
- customer_id: string (customer identifier)
- order_date: date (yyyy-MM-dd format)
- revenue: double (order revenue value in INR)
- product_cost: double (production cost in INR)
- profit_amount: double (profit calculated as revenue - product_cost)
- profit_margin: double (profit percentage margin, e.g. 0.35 = 35%)
- quantity: int (number of items in order)
- order_status: string ("Completed", "Cancelled", "Returned")
- delivery_days: int (actual shipping and delivery transit days)
- delivery_status: string ("Delivered", "In Transit", "Failed", "Returned")
- shipping_charge: double (freight/shipping cost in INR)
- payment_method: string ("UPI", "Credit Card", "Debit Card", "Net Banking", "Cash on Delivery")
- state: string (Indian state, e.g., "Karnataka", "Maharashtra", "Delhi")
- city: string (Indian city, e.g., "Bangalore", "Mumbai", "New Delhi")
- product_category: string ("Electronics", "Fashion", "Home Appliances", "Sports", "Beauty", "Books", "Toys", "Kitchen")
- brand: string (Brand names, e.g., "Samsung", "Apple", "Nike", "Sony")
- warehouse: string ("Warehouse Alpha", "Warehouse Beta", "Warehouse Gamma", "Warehouse Delta")
- discount_percent: double (discount percentage, e.g. 15.0 = 15%)
- tax_amount: double (applied GST or tax in INR)
- product_subcategory: string (subcategory text, e.g., "Accessories", "Footwear")
- unit_price: double (unit selling price of product)
- total_amount: double (gross bill amount including tax)
- product_rating: double (product quality reviews rating 1.0 - 5.0)`,

  customer: `Table: e_com.gold.customer_360
Description: Complete 360-degree demographic and activity profiling of customers. Use this for registrations, customer distributions, customer lifetime aggregates, loyalty points, satisfaction scores, ages, genders, and profiles.
Columns:
- customer_id: string (unique customer identifier)
- customer_name: string (full name of the customer)
- state: string (registration state)
- city: string (registration city)
- registration_date: date (yyyy-MM-dd)
- last_purchase_date: date (yyyy-MM-dd)
- total_revenue: double (cumulative money spent in INR)
- total_orders: int (number of historical orders completed)
- total_loyalty_points: int (accumulated loyalty points balance)
- avg_satisfaction_score: double (average support ticket rating, 1.0 - 5.0)
- customer_tenure_days: int (days active on platform)
- age: int (customer age)
- gender: string ("Male", "Female")
- customer_profile: string ("VIP", "Corporate", "Regular")
- churn_flag: int (0 = Active, 1 = Churned)
- avg_order_value: double (average spent per order)
- total_profit: double (net profit generated by customer)`,

  marketing: `Table: e_com.gold.marketing_summary
Description: Connects customers, orders, and products to marketing campaign conversions and billing transactions.
Columns:
- customer_id: string (unique customer identifier)
- order_id: string (unique order identifier)
- order_date: date (yyyy-MM-dd)
- product_category: string (product category sold)
- brand: string (brand name sold)
- final_bill_amount: double (bill total which represents conversions value)
Note: To group by channels (e.g. Google Ads, Facebook Ads, Email, organic), the client maps conversions by order index, but you can count conversions or sum final_bill_amount.`,

  delivery: `Table: e_com.gold.delivery_summary
Description: Shipping details, warehouses, and logistic transit records.
Columns:
- order_id: string (order identifier)
- customer_id: string (customer identifier)
- order_date: date (yyyy-MM-dd)
- warehouse: string (shipping warehouse name)
- delivery_status: string ("Delivered", "In Transit", "Failed", "Returned")
- delivery_days: int (delivery cycles duration in days)
- city: string (delivery destination city)
- state: string (delivery destination state)
- product_category: string (category being shipped)`,

  support: `Table: e_com.gold.support_summary
Description: Tracks support desk statistics, help tickets, and customer satisfaction ratings.
Columns:
- customer_id: string (customer identifier)
- order_id: string (order identifier)
- order_date: date (yyyy-MM-dd)
- customer_support_interactions: int (number of service messages/emails exchanged)
- customer_satisfaction_score: int (ticket CSAT rating, 1-5)
- product_category: string (category causing support issues)`,

  clickstream: `Table: e_com.gold.clickstream_summary
Description: Web logs representing browsing patterns and funnel drop-offs.
Columns:
- customer_id: string (customer identifier)
- order_date: date (yyyy-MM-dd)
- product_category: string (category viewed)
- cart_abandoned: string ("Yes" or "No")`,

  forecast: `Table: e_com.ml.sales_forecast
Description: Machine learning predicted sales revenues for upcoming dates.
Columns:
- forecast_date: string (yyyy-MM-dd format)
- predicted_revenue: double (predicted revenue in INR)
- lower_bound: double (confidence lower limit)
- upper_bound: double (confidence upper limit)
- model_version: string (ML model tag, e.g. "v3.1.0")
- mae_dollars: double (mean absolute error)
- mape_percent: double (mean absolute percentage error)`,

  recommendation: `Table: e_com.ml.product_recommendations
Description: AI-recommended products personalized for customers.
Columns:
- customer_id: string (customer identifier)
- product_id: string (recommended product SKU)
- product_details: string (product name details)
- brand: string (brand name)
- product_category: string (product category)
- score: double (recommendation match score, e.g., 0.89)
- recommendation_rank: int (1, 2, or 3 ranking)
- recommendation_date: string (yyyy-MM-dd)

Table: e_com.ml.product_affinities
Description: Association rule market basket co-purchasing statistics.
Columns:
- source_product: string (parent product name)
- recommended_product: string (co-purchased recommendation name)
- source_category: string (parent category)
- recommended_category: string (recommended category)
- affinity_score: double (co-purchase correlation score)`,

  churn: `Table: e_com.ml.churn_predictions
Description: Predictive retention flags indicating likelihood of customer churn.
Columns:
- customer_id: string (customer identifier)
- customer_name: string (customer name)
- churn_probability: double (churn likelihood score, 0.0 - 1.0)
- risk_level: string (contains emoji prefixes! The exact values in the database are '🔴 High Risk', '🟡 Medium Risk', '🟢 Low Risk'. When filtering by risk_level, always use these exact string values or use LIKE, e.g. risk_level LIKE '%High%')
- prediction_date: string (yyyy-MM-dd)
- model_version: string (model version)`,

  clv: `Table: e_com.ml.clv_predictions
Description: Predictive lifetime value scoring for customers.
Columns:
- customer_id: string (customer identifier)
- customer_name: string (customer name)
- predicted_clv_12m: double (predicted 12-month value in INR)
- clv_tier: string (contains emoji prefixes! The exact values in the database are '🏆 Platinum (Top 10%)', '🥇 Gold (Next 20%)', '🥈 Silver (Next 30%)', '🥉 Bronze (Bottom 40%)'. When filtering by clv_tier, always use these exact string values or use LIKE, e.g. clv_tier LIKE '%Platinum%')
- total_revenue: double (historical revenue in INR)
- prediction_date: string (yyyy-MM-dd)
- model_version: string (CLV model identifier)`
};

export function buildAgentPrompt(agentKey: string): string {
  const agent = AGENTS[agentKey] || AGENTS.sales;
  const schema = TABLE_SCHEMAS[agentKey] || TABLE_SCHEMAS.sales;

  return `You are the specialized AI Agent: "${agent.name}".
Your task is to write optimized, highly performant Databricks SQL based on a user's natural language question.

Your Business Domain Knowledge and Target Tables:
${schema}

Rules for SQL Generation:
1. Always generate a SINGLE valid Databricks SQL query.
2. ALWAYS qualify all table names exactly as shown (e.g. e_com.gold.sales_summary or e_com.ml.sales_forecast). Never write queries against unqualified tables like 'sales_summary'.
3. Do not invent columns. Only use the column names explicitly listed in the schema description above.
4. For text matches, use case-insensitive matching where appropriate (e.g., lower(state) = 'karnataka') or standard SQL queries.
5. In your SQL, write SELECT statements only. Never generate destructive statements (DDL/DML like INSERT, DELETE, UPDATE, DROP).
6. Always end your queries with a semicolon.
7. Return your response in a strict JSON format with this exact structure:
{
  "sql": "SELECT ...",
  "explanation": "Brief explanation of what the query calculates and which tables it reads.",
  "tables_used": ["e_com.gold.sales_summary"]
}

Important: Return ONLY the JSON object. Do not wrap in markdown code blocks like \`\`\`json. Do not include introductory text.`;
}
